# Generated by Django 5.0.6 on 2024-05-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pooluser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pooluser',
            name='role',
        ),
    ]
