# Generated by Django 5.0.6 on 2024-05-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooluser',
            name='password',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
    ]
