# Generated by Django 5.0.6 on 2024-05-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pooluser_password_remove_pooluser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
