# Generated by Django 5.0.6 on 2024-05-27 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscriptiontype_daily_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
