# Generated by Django 5.0.6 on 2024-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subscriptiontype_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooluser',
            name='age',
            field=models.DateField(),
        ),
    ]
